name: Publish to GitHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: create-json-service-account-read-only-test
      id: create-json-service-account-read-only-test
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "service-account-read-only-test.json"
        json: ${{ secrets.SERVICE_ACCOUNT_READ_ONLY_TEST }}
        dir: '/'
    - name: create-json-service-account-read-write-test
      id: create-json-service-account-read-write-test
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "service-account-read-write-test.json"
        json: ${{ secrets.SERVICE_ACCOUNT_READ_WRITE_TEST }}
        dir: '/'
    - name: create-json-config-bucket-test
      id: create-json-config-bucket-test
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "config-bucket-test.json"
        json: ${{ secrets.CONFIG_BUCKET_TEST }}
        dir: '/'
    - name: create-json-config-database-test
      id: create-json-config-database-test
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "config-database-test.json"
        json: ${{ secrets.CONFIG_DATABASE_TEST }}
        dir: '/'
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'oracle'
        cache: maven
    - name: Publish to GitHub Packages
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
